### ISSUE TITLE
Cannot provision on balenaOS 2.88.5

### ISSUE THREAD

**Issue by gabrielepmattia** [balena-io/open-balena#135]
I'm trying to provision a Raspberry Pi 4 but it does not attach to the fleet once booted. After searching and debugging I discovered that the API call to api.example.com/connectivity-check does not return the 'Date' header for allowing the Raspberry to update the date and  then correctly pulling the containers or using HTTPS with a new certificate.

Can I simply bump the open-balena-api image to latest version 0.188.3 in the file /compose/versions and still getting the server working? Or is it planned to support versions of balenaOS >= 2.88.x?

https://github.com/balena-io/open-balena/blob/39f7f6b0cc8d323b0fe604c3fc54a5d0ea723fc6/compose/versions#L1

**Comment by bartversluijs** [comment]
Hi @gabrielepmattia,

I've been busy with upgrading my openBalena instance, and there were some problems trying to upgrade to the newest API service (See [issue 926](https://github.com/balena-io/open-balena-api/issues/926), [PR 972](https://github.com/balena-io/open-balena-api/pull/927) & [PR 928](https://github.com/balena-io/open-balena-api/pull/928)).

One of the problems was that the OpenBalena API container can't start because of a wrong dependency while starting.
The other one is missing permissions while provisioning a device, because of a hook.

So, for the time being, I'd suggest to use an older BalenaOS version until this is fixed. Once this is fixed, I'll upgrade my OpenBalena instance and create a PR with the newest versions after testing the upgrade.

**Comment by gabrielepmattia** [comment]
Thanks @bartversluijs! I hope that it will get fixed soon, in the meanwhile I will try to use balenaOS versions <= 2.80.10 that is the last one released before June 30, 2021, that is the last update of this repo. I hope that they will work on Raspberry Pi 4.

I also think that this repo should have a compatibility alert on the README.md, even for the maximum (tested) version, not only for the minimum.

**Comment by bartversluijs** [comment]
As an update, once #137 is merged, this will fix this issue.

**Comment by bartversluijs** [comment]
This is fixed by #137. Upgrade to v3.6.0 of open-balena and you'll be able to provision balenaOS 2.88.5 devices :)

**Comment by ab77** [comment]
Solved.
