### ISSUE TITLE
Registry without volume

### ISSUE THREAD

**Issue by bartversluijs** [balena-io/open-balena#138]
Hi all,

The registry service depends on a volume, but is this necessary?
I've been using the registry for quite a while now in my openBalena instance, but the `/data` directory is still empty, because everything is stored on an external S3 storage.

So my question is, is there a reason why the registry service has a volume attached to it?
My first thought was for caching purposes, e.g. the registry downloads the files from the S3 storage and keeps them "hot" for a while, but that's not the case afaik.
 
If not, I'd gladly create a PR to remove this volume!

---

Thinking about it, even if it was for caching purposes, even then a volume isn't necessary. If the container gets destroyed, the only thing lost is the cache. But that isn't a problem, because it's cache 😄

**Comment by dfunckt** [comment]
The registry [will use S3 if configured that way and otherwise fallback to filesystem](https://github.com/balena-io/open-balena-registry/blob/master/config/confd/templates/docker-registry.yml.tmpl#L38-L54) storage. It doesn't hurt but I can see how it can be confusing to provide *both* options to registry in openBalena, even though the latter is effectively ignored. I'd be happy to accept a PR to remove it 👍

**Comment by bartversluijs** [comment]
Thanks for the clarification and linking to the code!
I'll create a PR to remove the volumes for the registry, because openBalena will use S3 by default. 

So I agree it's confusing to provide both options. In my opinion, if you'd like to use the file system, you should do that yourself in the `config/docker-compose.yml` instead of having it built-in.

---

For the Kubernetes Helm chart, this is also a big difference, because the registry is then stateless and doesn't need a persistent volume. Which is great! Fixed that in [bartversluijs/open-balena - PR #6](https://github.com/bartversluijs/open-balena/pull/6).
