### ISSUE TITLE
Supported devices

### ISSUE THREAD

**Issue by markdegrootnl** [balena-io/open-balena#147]
In the readme it states that Open Balena supports a subset of devices:

> Supported devices: Raspberry Pi family, the Intel NUC, the NVIDIA Jetson TX2, and the balenaFin

What is exactly the limitation? Is this just to encourage people using the paid version or is there a technical impediment? Since the project is open source, how would one add more supported devices?

Similar questions:

- https://forums.balena.io/t/devices-supported-in-openbalena/4581
- https://forums.balena.io/t/adding-custom-device-to-openbalena-instance/189269/23
- https://forums.balena.io/t/supported-devices/328982
- #133

**Comment by dfunckt** [comment]
There's no limitation -- in theory openBalena supports the same set of devices balenaCloud does. In practice, we cannot advertise support for all of them because it's currently impractical to test them all out like we do for balenaCloud. This will hopefully change in the future. What device are you interested in?

> how would one add more supported devices?

Adding support for new devices is non-trivial -- irrespective of whether it's for openBalena or balenaCloud. The first step would be to get balenaOS running on the device and the quickest way to do that is to start from a balenaOS variant that appears to be most compatible to the device you want to add support for. You can get quite far by masquerading as a device that is currently supported as it trivially solves the problem of connecting your custom balenaOS to the backend. That's all off the top my head. For more information, the best approach is to use the forums where you can get hold of the OS team to help you along the way.

**Comment by markdegrootnl** [comment]
Here is more information: https://forums.balena.io/t/supported-devices-in-open-balena/357665/20
