### ISSUE TITLE
OpenBalena - Mention KVM as Preferred Virtualization

### ISSUE THREAD

**Issue by dtischler** [balena-io/open-balena#166]
A user had issues deploying OpenBalena when using OpenVZ and Virtuozzo based VPS's, however it worked right away when he attempted a KVM based virtual server on attempt number three.  Forum post is located here:  https://forums.balena.io/t/180828

It might be helpful if we added a small note that we recommend a KVM based server to the Getting Started Guide: https://www.balena.io/open/docs/getting-started

**Comment by ab77** [comment]
Since all of our components are still running systemd in containers and systemd is not suitable for containers, [we won't be supporting cgroups v2](https://open-balena.pages.dev/getting-started#install-openbalena-on-the-server). We would more likely start moving slowly to a more container friendly init system, like s6.
