### ISSUE TITLE
kubernetes deployment support

### ISSUE THREAD

**Issue by rugwirobaker** [balena-io/open-balena#6]
I don't know your roadmap but supporting more deployment options would bring more people to the community. And the kubernetes community is one of the largest. Plus it would help integrate open-balena in the current kube stacks.

**Comment by dfunckt** [comment]
@rugwirobaker we do plan to support more deployment options and kubernetes is at the top of the list and, to the best of my knowledge, it will be coming before openBalena goes out of beta.

**Comment by dfunckt** [comment]
I don’t think there are technical issues — an openBalena deployment can already be described with a docker-compose file, so I expect k8s support to be straightforward. We’ll be revamping the deployment workflow of openBalena in the coming weeks though, and k8s needs to fit into that, hence the delay.

**Comment by IonBazan** [comment]
@dfunckt I am a bit worried about that because currently OpenBalena is using systemd and all the services are being run in privileged mode. K8s supports privileged containers, however it does not seem to be a good idea. Is it possible to run Open Balena without systemd, unprivileged?

**Comment by dfunckt** [comment]
@IonBazan we'll soon not require the services to run as privileged. Regarding systemd, I don't think we're currently willing to migrate away but might worth to reconsider. What issues do you have in mind with systemd and k8s?

**Comment by ArkeologeN** [comment]
@dfunckt it seems a couple of months since the thread started. Is there any update on this topic?

**Comment by dfunckt** [comment]
We're making progress but nothing concrete yet @ArkeologeN. We're working on a new tool to handle platform deployment which will support different targets, and k8s (as well as docker-compose) is one of them, but it's taking a while.

**Comment by Sharique-Hasan** [comment]
@dfunckt I got enlightened about the progress on the deployment part via this thread. Since our whole infrastructure runs on k8 so we need this open-balena deployment to be in k8 as well.

We tried using `kompose convert` to convert docker-compose into k8 deployment files. Our ingress was able to redirect the traffic but looks like ingress is unable to locate upstream server for open-balena and all we got is this:

```
{"message":"failure to get a peer from the ring-balancer"}
```

Your help would be greatly appreciated

**Comment by rusenask** [comment]
should be a lot easier to write the k8s manifest yourself than use kompose convert :)

**Comment by Sharique-Hasan** [comment]
@rusenask I did try that too and the service didn't even come up online. With kompose the service even come up online.

**Comment by gercorri** [comment]
@dfunckt is there any more progress on the k8s deployment option?

**Comment by bartversluijs** [comment]
I've been busy with creating a Kubernetes version of openBalena for the last week now, but with the current setup, it's (nearly) impossible. I've posted my progress [on the forums](https://forums.balena.io/t/kubernetes-for-scaling/132102), where I had some success, but some configurations (like VPN over 443) are as good as impossible to implement in Kubernetes using Ingress.

Any help would be appreciated from other Kubernetes developers. So feel free to contact me.

**Comment by mehdisadeghi** [comment]
@bartversluijs great effort, indeed. I was wondering whether it's possible to use WireGuard for tunneling in balena. It's much simpler.

**Comment by bartversluijs** [comment]
Just to let everyone that's interested in this know, I've created a working version of open-balena on Kubernetes. I've [posted this on the forum](https://forums.balena.io/t/kubernetes-for-scaling/132102/40). It works without much effort, but it isn't 100% done yet.

And @mehdisadeghi, I'm not a Balena team member, so I don't know if that's possible at all. I'm not familiar with WireGuard. But because open-balena is open-source, you should try it for yourself!

**Comment by bartversluijs** [comment]
As I'm finishing my Helm chart for Kubernetes for the newest release of openBalena, is there a way we can make this an official supported Kubernetes deployment option and merged into this repository? 

Would be great to talk about an official release of it and discuss this with the openBalena maintainers!

I'll create a PR once it's finished and maybe this issue can then be closed.

**Comment by bdsoha** [comment]
Any updates on this?

**Comment by ab77** [comment]
I am going to close this, since https://kompose.io/ has a direct docker-compose=>kubernetes functionality that works reasonably well. Please consider contributing via standard PR process if you are still interested in this feature or joining this [issue](https://github.com/balena-io/open-balena/pull/124) going forward.
